var searchButton = document.getElementById("submit"),
  searchText = document.getElementById("search");

var items = [
  { text: "აბსოლუტური", id: "absoluturi" },
  { text: "აბსოლიტური", id: "absolituri" },
  { text: "ავამოძრაო", id: "avamodzrao" },
  { text: "ავამოძრავო", id: "avamodzravo" },
  { text: "ავ-კარგი", id: "av-kargi" },
  { text: "ავკარგი", id: "avkargi" },
  { text: "ითვალწუნებს", id: "itvalwunebs" },
  { text: "ითვალისწუნებს", id: "itvaliswunebs" },
  { text: "აკურატული", id: "akuratuli" },
  { text: "აკურატულნი", id: "akuratulni" },
  { text: "ასმევს", id: "asmevs" },
  { text: "ალევინებს", id: "alevinebs" },
  { text: "ამ დროიდან", id: "am-droidan" },
  { text: "ამდროიდან", id: "amdroidan" },
  { text: "ამდროინდელი", id: "amdroindeli" },
  { text: "ამ დროინდელი", id: "am-droindeli" },
  { text: "ამოგლეჯს", id: "amoglejs" },
  { text: "ამოჰგლეჯს", id: "amohglejs" },
  { text: "ამოთხუპნილი", id: "amotxupnili" },
  { text: "ამოთხუპნული", id: "amotxupnuli" },
  { text: "ამოჩიჩქნის", id: "amochichqnis" },
  { text: "ამოსჩიჩქნის", id: "amoschichqnis" },
  { text: "ამოჩქეფს", id: "amochqefs" },
  { text: "ამოსჩქეფს", id: "amoschqefs" },
  { text: "ამოცვივდა", id: "amocvivda" },
  { text: "ამოსცვივდა", id: "amoscvivda" },
  { text: "ამოჰბერვია", id: "amohbervia" },
  { text: "ამობერვია", id: "amobervia" },
  { text: "ამოჰბუგვია", id: "amohbugvia" },
  { text: "ამობუგვია", id: "amobugvia" },
  { text: "ამოჰბურცვია", id: "amohburcvia" },
  { text: "ამობურცვია", id: "amoburcvia" },
  { text: "ამოჰყავს", id: "amohyavs" },
  { text: "ამოყავს", id: "amoyavs" },
  { text: "ამოჰკორტნის", id: "amohkortnis" },
  { text: "ამოკორტნის", id: "amokortnis" },
  { text: "ანახვებს", id: "anaxvebs" },
  { text: "ანახებს", id: "anaxebs" },
  { text: "ანახვოს", id: "anaxvos" },
  { text: "ანახოს", id: "anaxos" },
  { text: "ანახვებდა", id: "anaxvebda" },
  { text: "ანახებდა", id: "anaxebda" },
  { text: "ანახვინა", id: "anaxvina" },
  { text: "ანახინა", id: "anaxina" },
  { text: "ანეკდოტი", id: "anekdoti" },
  { text: "ანეგდოტი", id: "anegdoti" },
  { text: "ავითარებს", id: "avitarebs" },
  { text: "ანვითარებს", id: "anvitarebs" },
  { text: "აზოგადებს", id: "azogadebs" },
  { text: "ანზოგადებს", id: "anzogadebs" },
  { text: "ათავისუფლებს", id: "atavisuflebs" },
  { text: "ანთავისუფლებს", id: "antavisuflebs" },
  { text: "ანოყივრებს", id: "anoyivrebs" },
  { text: "ანოყიერებს", id: "anoyierebs" },
  { text: "ასახიერებს", id: "asaxierebs" },
  { text: "ანსახიერებს", id: "ansaxierebs" },
  { text: "ასხვავებს", id: "asxvavebs" },
  { text: "ანსხვავებს", id: "ansxvavebs" },
  { text: "აცვიფრებს", id: "acvifrebs" },
  { text: "ანცვიფრებს", id: "ancvifrebs" },
  { text: "ახორციელებს", id: "axorcielebs" },
  { text: "ანხორციელებს", id: "anxorcielebs" },
  { text: "არა აქვს", id: "ara-aqvs" },
  { text: "არ აქვს", id: "ar-aqvs" },
  { text: "არასგზით", id: "arasgzit" },
  { text: "არაგზით", id: "aragzit" },
  { text: "არა და არა", id: "ara-da-ara" },
  { text: "არადაარა", id: "aradaara" },
  { text: "არადროული", id: "aradrouli" },
  { text: "არა დროული", id: "ara-drouli" },
  { text: "არაერთგზის", id: "araertgzis" },
  { text: "არა ერთგზის", id: "ara-ertgzis" },
  { text: "არაერთი", id: "araerti" },
  { text: "არა ერთი", id: "ara-erti" },
  { text: "არაერთხელ", id: "araertxel" },
  { text: "არა ერთხელ", id: "ara-etxel" },
  { text: "არა მარტო", id: "ara-marto" },
  { text: "არამარტო", id: "aramarto" },
  { text: "არამც და არამც", id: "aramc-da-aramc" },
  { text: "არამცდაარამც", id: "aramcdaaramc" },
  { text: "არარეალური", id: "ararealuri" },
  { text: "არა რეალური", id: "ara-realuri" },
  { text: "არასდროს", id: "arasdros" },
  { text: "არასოდეს", id: "arasodes" },
  { text: "არასწორი", id: "araswori" },
  { text: "არა სწორი", id: "ara-swori" },
  { text: "არა უადრეს", id: "ara-uadres" },
  { text: "არაუადრეს", id: "arauadres" },
  { text: "არა უშავს", id: "ara-ushavs" },
  { text: "არაუშავს", id: "araushavs" },
  { text: "არც კი", id: "arc-ki" },
  { text: "არცკი", id: "arcki" },
  { text: "არა უგვიანეს", id: "ara-ugvianes" },
  { text: "არაუგვიანეს", id: "araugvianes" },
  { text: "არა უდიდეს", id: "ara-udides" },
  { text: "არაუდიდეს", id: "araudides" },
  { text: "არყოლა", id: "aryola" },
  { text: "არ ყოლა", id: "ar-yola" },
  { text: "არყოფნა", id: "aryofna" },
  { text: "არ ყოფნა", id: "ar-yofna" },
  { text: "არცთუ", id: "arctu" },
  { text: "არც თუ", id: "arc-tu" },
  { text: "ასე თუ ისე", id: "ase-tu-ise" },
  { text: "ასეთუისე", id: "asetuise" },
  { text: "ას ორმოცდაათი", id: "as-ormocdaati" },
  { text: "ასორმოცდაათი", id: "asormocdaati" },
  { text: "ასორმოცდამეათე", id: "asormocdameate" },
  { text: "ას ორმოცდამეათე", id: "as-ormocdameate" },
  { text: "ასფალტი", id: "asfalti" },
  { text: "ასვალტი", id: "asvalti" },
  { text: "ასჩუყებია", id: "aschuyebia" },
  { text: "აჩუყებია", id: "achuyebia" },
  { text: "ასძაგძაგებია", id: "asdzagdzagebia" },
  { text: "აძაგძაგებია", id: "adzagdzagebia" },
  { text: "ასწია", id: "aswia" },
  { text: "აწია", id: "awia" },
  { text: "აწონის", id: "awonis" },
  { text: "ასწონის", id: "aswonis" },
  { text: "ასწყვეტია", id: "aswyvetia" },
  { text: "აწყვეტია", id: "awyvetia" },
  { text: "ასჭრელებია", id: "aswrelebia" },
  { text: "აჭრელებია", id: "awrelebia" },
  { text: "ატეხს", id: "atexs" },
  { text: "ატეხავს", id: "atexavs" },
  { text: "აღუზრდის", id: "aghuzrdis" },
  { text: "აუზრდის", id: "auzrdis" },
  { text: "აუნუსხავი", id: "aunusxavi" },
  { text: "აღუნუსხავი", id: "aghunusxavi" },
  { text: "აუპყრობს", id: "aupyrobs" },
  { text: "აღუპყრობს", id: "aghupyrobs" },
  { text: "აქეთობას", id: "aqetobas" },
  { text: "აქეთობისას", id: "aqetobisas" },
  { text: "აქედან", id: "aqedan" },
  { text: "აქიდან", id: "aqidan" },
  { text: "აღვკვეთ", id: "aghvkvet" },
  { text: "ავღკვეთ", id: "avghkvet" },
  { text: "აღვნუსხავ", id: "aghvnusxav" },
  { text: "ავღნუსხავ", id: "avghnusxav" },
  { text: "აღვკვეც", id: "aghkvec" },
  { text: "ავღკვეც", id: "avghkvec" },
  { text: "აღვმართავ", id: "aghvmartav" },
  { text: "ავღმართავ", id: "avghmartav" },
  { text: "აღვნიშნავ", id: "aghvnishnav" },
  { text: "ავღნიშნავ", id: "avghnishnav" },
  { text: "აღვშფოთდები", id: "aghvshfotdebi" },
  { text: "ავღშფოთდები", id: "avghshfotdebi" },
  { text: "აღვძრავ", id: "aghvdzrav" },
  { text: "ავღძრავ", id: "avghdzrav" },
  { text: "აღვწერ", id: "aghvwer" },
  { text: "ავღწერ", id: "avghwer" },
  { text: "აღვჭურავ", id: "aghvwurav" },
  { text: "ავღჭურავ", id: "avghwurav" },
  { text: "აღუნუსხავს", id: "aghunusxavs" },
  { text: "აღუნუსხია", id: "aghunusxia" },
  { text: "აღუჭურავს", id: "aghuwuravs" },
  { text: "აღუჭურვია", id: "aghuwurvia" },
  { text: "აძღებს", id: "adzghebs" },
  { text: "აძღობს", id: "adzghobs" },
  { text: "აწ განსხვენებული", id: "aw-gansvenebuli" },
  { text: "აწგანსვენებული", id: "awgansvenebuli" },
  { text: "ახლავე", id: "axlave" },
  { text: "ეხლავე", id: "exlave" },
  { text: "ახლად აგებული", id: "axlad-agebuli" },
  { text: "ახლადაგებული", id: "axladagebuli" },
  { text: "ახლომახლო", id: "axlomaxlo" },
  { text: "ახლო მახლო", id: "axlo-maxlo" },
  { text: "სვამს", id: "svams" },
  { text: "აჯენს", id: "ajens" },
  { text: "აჰგიზგიზებია", id: "ahgizgizebia" },
  { text: "აგიზგიზებია", id: "agizgizebia" },
  { text: "აჰგლეჯია", id: "ahglejia" },
  { text: "აგლეჯია", id: "aglejia" },
  { text: "აჰკანკალებია", id: "ahkankalebia" },
  { text: "აკანკალებია", id: "akankalebia" },
  { text: "აჰკიდებია", id: "ahkidebia" },
  { text: "აკიდებია", id: "akidebia" },
  { text: "აჰყოლია", id: "ahyolia" },
  { text: "აყოლია", id: "ayolia" },
  { text: "აჰყუდებია", id: "ahyudebia" },
  { text: "აყუდებია", id: "ayudebia" },
  { text: "აღტყინებული", id: "aghtyinebuli" },
  { text: "აღტკინებული", id: "aghtkinebuli" },

  { text: "ბაფთა", id: "bafTa" },
  { text: "ბაფტა", id: "bafta" },
  { text: "ბალეტმაისტერი", id: "baletmaisteri" },
  { text: "ბალეტმეისტერი", id: "baletmeisteri" },
  { text: "ბალნეოლოგი", id: "balneologi" },
  { text: "ბალნელოგი", id: "balnelogi" },
  { text: "ბანკნოტი", id: "banknoti" },
  { text: "ბაკნოტი", id: "baknoti" },
  { text: "ბარდ-ეკალი", id: "bard-ekali" },
  { text: "ბარდეკალი", id: "bardekali" },
  { text: "ბაღჩა", id: "baghcha" },
  { text: "ბახჩა", id: "baxcha" },
  { text: "ბდღვნა", id: "bdghvna" },
  { text: "ბღვდნა", id: "bghdvna" },
  { text: "ბედშავი", id: "bedshavi" },
  { text: "ბედ-შავი", id: "bed-shavi" },
  { text: "ბებიამისი", id: "bebiamisi" },
  { text: "ბებია-მისი", id: "bebia-misi" },
  { text: "ბებიაქალი", id: "bebiaqali" },
  { text: "ბებია-ქალი", id: "bebia-qali" },
  { text: "ბერ-მონაზონი", id: "ber-monazoni" },
  { text: "ბერმონაზონი", id: "bermonazoni" },
  { text: "ბერად", id: "berad" },
  { text: "ბერათ", id: "berat" },
  { text: "ბეჩაობა", id: "bechaoba" },
  { text: "ბეჩავობა", id: "bechavoba" },
  { text: "ბოხჩა", id: "boxcha" },
  { text: "ბოღჩა", id: "boghcha" },
  { text: "ბობოქრად", id: "boboqrad" },
  { text: "ბობოქრათ", id: "boboqrat" },
  { text: "ბოძებშუა", id: "bodzebshua" },
  { text: "ბოძებ-შუა", id: "bodzeb-shua" },
  { text: "ბგერათაღწარმოება", id: "bgerataghwarmoeba" },
  { text: "ბგერათ-აღწარმოება", id: "bgerat-aghwarmoeba" },
  { text: "ბზარგაჩენილი", id: "bzargachenili" },
  { text: "ბზარ-გაჩენილი", id: "bzar-gachenili" },
  { text: "ბზარშეპარული", id: "bzarsheparuli" },
  { text: "ბზარ-შეპარული", id: "bzar-sheparuli" },
  { text: "ბიათლონი", id: "biaTloni" },
  { text: "ბიატლონი", id: "biatloni" },
  { text: "ბლაგვკბილა", id: "blagvkbila" },
  { text: "ბლაგვ-კბილა", id: "blagv-kbila" },
  { text: "ბლაგვკუთხა", id: "blagvkutxa" },
  { text: "ბლაგვ-კუთხა", id: "blagv-kutxa" },
  { text: "ბლაგვპირა", id: "blagvpira" },
  { text: "ბლაგვ-პირა", id: "blagv-pira" },
  { text: "ბნედა", id: "bneda" },
  { text: "ბნედვა", id: "bnedva" },
  { text: "ბნედამორეული", id: "bnedamoreuli" },
  { text: "ბნედა-მორეული", id: "bneda-moreuli" },
  { text: "ბნედს", id: "bneds" },
  { text: "ბნედავს", id: "bnedavs" },
  { text: "ბჟღვრიალებს", id: "bdjghvrialebs" },
  { text: "ბჟღვრიალეფს", id: "bdjghvrialefs" },
  { text: "ბრაგაბრუგი", id: "bragabrugi" },
  { text: "ბრაგა-ბრუგი", id: "braga-brugi" },
  { text: "ბრადიკარდია", id: "bradikardia" },
  { text: "ბრადი-კარდია", id: "bradi-kardia" },
  { text: "ბღავი", id: "bghavi" },
  { text: "ბღავიხარ", id: "bghavixar" },
  { text: "ბწკენა", id: "bwkena" },
  { text: "ბრწკენა", id: "brwkena" },
];

function searchForItem(query) {
  for (var i = 0; i < items.length; i++) {
    if (items[i].text.indexOf(query) !== -1) {
      document.getElementById(items[i].id).classList.add("searched");
      setTimeout(function () {
        document.getElementById(items[i].id).classList.remove("searched");
      }, 5000);
      return document.getElementById(items[i].id);
    }
  }
}

searchButton.addEventListener("click", function () {
  var query = searchText.value,
    item = searchForItem(query);
  if (typeof item !== "undefined") {
    item.scrollIntoView({ behavior: "smooth", block: "center" });
  } else {
    alert("თქვენ მიერ შეყვანილი სიტყვა ვერ მოიძებნა!");
  }
});
